### ISSUE TITLE
Running websocat with localhost:3000 error 

### ISSUE THREAD

**Issue by mwilc0x** [tsidea/http-ws-server-rs#1]
Hi,

Thank you for this clear and helpful article and example!

Not sure if this is a local configuration thing, 
but one thing I ran into is having to run `websocat ws://127.0.0.1:3000/ws_echo`

```
$ websocat --version
websocat 1.9.0
$ websocat ws://localhost:3000/ws_echo
websocat: WebSocketError: I/O failure
websocat: error running
```

```
$ websocat ws://127.0.0.1:3000/ws_echo
hello
hello
```

**Comment by tsidea** [comment]
Thanks for pointing that out. It turns out this is an [issue](https://github.com/vi/websocat/issues/23) with websocat. I've updated the article.
